language: go

env:
  - DEP_VERSION="0.4.1"

cache:
  directories:
    - $GOPATH/pkg/dep

go_import_path: github.com/atlassian/escalator
go:
  - master
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - make setup

jobs:
  include:
    - stage: test
      script: make test
    - stage: test
      script: make test-race
    - stage: test
      script: make test-vet
    - stage: build
      script: make build
    - state: docker
      script: make docker
      go: master
